services:
  - type: web
    name: aadhi-store
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2m09uf5r7bs73e68p4g-a:5432/aadhi_db
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: aadhi-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: aadhi-db
          property: password
databases:
  - name: aadhi-db
    plan: free
