spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: tenant_default

server:
  port: ${PORT:8080}

logging:
  file:
    path: logs/
    name: logs/application.log
