spring:
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: ${PORT:8080}

logging:
  file:
    path: logs/
    name: logs/application.log
